---
pages:
- blog/online-assets-after-your-death.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- type: tag_list
  name: categories
  label: Categories
- type: tag_list
  name: tags
  label: Tags
- type: text
  name: type
  label: Type
  default: post
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
